theme: jekyll-theme-merlot
title: Ian Hawke's Revenge
description: After Ian Hawke's first attack on this world he was deafeated by a cool gamer. Now he's taking all the souls of the dead chipmuncks in Chip Invaders and putting them into robots. Now only a cool gamer like you can deafeat him! Go and save the universe!
show_downloads: True
